package com.mycompany.groupprojectpart4;

import com.mysql.cj.jdbc.exceptions.MysqlDataTruncation;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jacob
 */
public class Launcher extends javax.swing.JFrame {
    public static String databasepw = "database";
    public static Connection connection;
    

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();
        refresh();
                try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/groupsixproject", "root", databasepw);        
                
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mandatoryFieldsDialog = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gamesList = new javax.swing.JList<>();
        newGameButton = new javax.swing.JButton();
        saveGameButton = new javax.swing.JButton();
        gameIDLabel = new javax.swing.JLabel();
        gameTypeBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gameLocationBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gameDateMMBox = new javax.swing.JTextField();
        gameDateDDBox = new javax.swing.JTextField();
        gameDateYYYYBox = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        gameHostList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        gameIDValue = new javax.swing.JTextField();
        deleteGameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("You must complete all fields to save.");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setRequestFocusEnabled(false);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mandatoryFieldsDialogLayout = new javax.swing.GroupLayout(mandatoryFieldsDialog.getContentPane());
        mandatoryFieldsDialog.getContentPane().setLayout(mandatoryFieldsDialogLayout);
        mandatoryFieldsDialogLayout.setHorizontalGroup(
            mandatoryFieldsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mandatoryFieldsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mandatoryFieldsDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mandatoryFieldsDialogLayout.setVerticalGroup(
            mandatoryFieldsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mandatoryFieldsDialogLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jTabbedPane1.setToolTipText("");

        gamesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        gamesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                gamesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(gamesList);

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        saveGameButton.setText("Save Game");
        saveGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameButtonActionPerformed(evt);
            }
        });

        gameIDLabel.setText("Game ID:");

        gameTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Competitive", "Casual" }));

        jLabel2.setText("Game type:");

        jLabel3.setText("Game location:");

        gameLocationBox.setToolTipText("");
        gameLocationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameLocationBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Game date (MM/DD/YYYY):");

        gameDateMMBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameDateMMBoxActionPerformed(evt);
            }
        });

        gameDateDDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameDateDDBoxActionPerformed(evt);
            }
        });

        gameDateYYYYBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameDateYYYYBoxActionPerformed(evt);
            }
        });

        gameHostList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        gameHostList.setDropMode(javax.swing.DropMode.ON);
        jScrollPane4.setViewportView(gameHostList);

        jLabel5.setText("Game host:");

        gameIDValue.setEditable(false);
        gameIDValue.setEnabled(false);
        gameIDValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameIDValueActionPerformed(evt);
            }
        });

        deleteGameButton.setText("Delete Game");
        deleteGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGameButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        jLabel6.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGameButton))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameLocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gameIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gameDateMMBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameDateDDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameDateYYYYBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameIDLabel)
                            .addComponent(jLabel5)
                            .addComponent(gameIDValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gameTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gameLocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gameDateMMBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gameDateDDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gameDateYYYYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newGameButton)
                                    .addComponent(saveGameButton)
                                    .addComponent(deleteGameButton)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Games", jPanel1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(604, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cards", jPanel2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(604, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Decks", jPanel3);

        getContentPane().add(jTabbedPane1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // TODO add your handling code here:
        gameIDValue.setText("");
        gameTypeBox.setSelectedIndex(0);
        gameLocationBox.setText("");
        gameDateMMBox.setText("");
        gameDateDDBox.setText("");
        gameDateYYYYBox.setText("");
        gameHostList.clearSelection();
        gamesList.clearSelection();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void gameLocationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameLocationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameLocationBoxActionPerformed

    private void gameDateDDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameDateDDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameDateDDBoxActionPerformed

    private void gameDateYYYYBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameDateYYYYBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameDateYYYYBoxActionPerformed

    private void gamesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_gamesListValueChanged
        // TODO add your handling code here:
        String value = gamesList.getSelectedValue();
        if (value != null) {
            String[] valueArr = value.split(" - ");
            String query = "select * from games natural join users where gameHost = userID AND gameDate=\"" + valueArr[0] + "\" AND gameLoc=\"" + valueArr[1] + "\" AND gameType=\"" + valueArr[2] + "\"";
            try {
                ResultSet rs = connection.createStatement().executeQuery(query);
                if (rs.next()) {
                    System.out.println(rs.getString("gameLoc"));
                    gameIDValue.setText(rs.getString("gameID"));
                    switch (rs.getString("gameType")) {
                        case "Competitive":
                            gameTypeBox.setSelectedIndex(0);
                            break;
                        case "Casual":
                            gameTypeBox.setSelectedIndex(1);
                            break;
                        default:
                            gameTypeBox.setSelectedIndex(0);
                    }
                    gameLocationBox.setText(rs.getString("gameLoc"));
                    String[] dateArr = rs.getString("gameDate").split("-");
                    gameDateMMBox.setText(dateArr[1]);
                    gameDateDDBox.setText(dateArr[2]);
                    gameDateYYYYBox.setText(dateArr[0]);
                    gameHostList.setSelectedValue(rs.getString("userID") + " - " + rs.getString("fname") + " " + rs.getString("lname"), true);
                }
            } catch (Exception exception) {
                exception.printStackTrace();
            }
        }
        

        
        
    }//GEN-LAST:event_gamesListValueChanged

    private void saveGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameButtonActionPerformed
        // TODO add your handling code here:
        try {
        String gameType = gameTypeBox.getSelectedItem().toString();
        String gameDate = gameDateYYYYBox.getText() + "-" + gameDateMMBox.getText() + "-" + gameDateDDBox.getText();
        String gameLoc = gameLocationBox.getText();
        String gameHost = gameHostList.getSelectedValue().split(" - ")[0];
        String query;
        String id = gameIDValue.getText().toLowerCase();
        System.out.println("ID = " + id);
        if (!id.isEmpty()) {
            query = "update games set gameType = \""
                    + gameType 
                    + "\", gameDate = \""
                    + gameDate 
                    + "\", gameLoc = \""
                    + gameLoc 
                    + "\", gameHost = \""
                    + gameHost
                    + "\" where gameID = \"" 
                    + id + "\"";
                    
        } else {
            query = "insert into games (gameType, gameDate, gameLoc, gameHost) values (\""
                    + gameTypeBox.getSelectedItem().toString() + "\", \""
                    + gameDateYYYYBox.getText() + "-"
                    + gameDateMMBox.getText() + "-"
                    + gameDateDDBox.getText() + "\", \""
                    + gameLocationBox.getText() + "\", \""
                    + gameHostList.getSelectedValue().split(" - ")[0]
                    + "\");";
        }
            int recUpdated = connection.createStatement().executeUpdate(query);
            System.out.println(query + " resulted in records updated: " + recUpdated);
            refresh();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Failed to save. Ensure all fields are filled out.");
        } catch (MysqlDataTruncation e) {
            JOptionPane.showMessageDialog(this, "Failed to save. Invalid data format.\n"
                    + "Details: " + e.getMessage());
        } catch (Exception exception) {
            exception.printStackTrace();
        }


    }//GEN-LAST:event_saveGameButtonActionPerformed

    private void gameIDValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameIDValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameIDValueActionPerformed

    private void deleteGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGameButtonActionPerformed
        // TODO add your handling code here:
        String id = gameIDValue.getText().toLowerCase();
        String query = "delete from games where gameID = \"" + id + "\"";
        try {
            connection.createStatement().executeUpdate(query);
            refresh();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }//GEN-LAST:event_deleteGameButtonActionPerformed

    private void gameDateMMBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameDateMMBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameDateMMBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });
    }
    

    
    public void refresh(){
      try {
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/groupsixproject", "root", databasepw);
                    
                    //Get games list from DB and refresh
                    String query = "select * from users natural join games where games.gameHost = users.userID order by gameDate desc";
                    Statement sta = connection.createStatement();
                    ResultSet rs = sta.executeQuery(query);  
                    DefaultListModel listModel;
                    listModel = new DefaultListModel();
                    while (rs.next()) {
                        listModel.addElement(rs.getString("gameDate") + " - " + rs.getString("gameLoc") + " - " + 
                      rs.getString("gameType")); 
                    }
                    gamesList.setModel(listModel);
                    
                    
                    query = "select * from users";
                    sta = connection.createStatement();
                    rs = sta.executeQuery(query);  
                    listModel = new DefaultListModel();
                    while (rs.next()) {
                        listModel.addElement(rs.getString("userID") + " - " + rs.getString("fname") + " " + 
                      rs.getString("lname")); 
                    }
                    gameHostList.setModel(listModel);
                
                    connection.close();
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteGameButton;
    private javax.swing.JTextField gameDateDDBox;
    private javax.swing.JTextField gameDateMMBox;
    private javax.swing.JTextField gameDateYYYYBox;
    private javax.swing.JList<String> gameHostList;
    private javax.swing.JLabel gameIDLabel;
    private javax.swing.JTextField gameIDValue;
    private javax.swing.JTextField gameLocationBox;
    private javax.swing.JComboBox<String> gameTypeBox;
    private javax.swing.JList<String> gamesList;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog mandatoryFieldsDialog;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton saveGameButton;
    // End of variables declaration//GEN-END:variables
}
